spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/railway}}
    username: ${PGUSER:${SPRING_DATASOURCE_USERNAME:postgres}}
    password: ${PGPASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 60000
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migrations

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    name: ${TELEGRAM_BOT_NAME}
    long-polling:
      timeout: 10
      limit: 20
      max-threads: 2

app:
  security:
    admin-telegram-ids: ${ADMIN_TELEGRAM_IDS:2056410944}

server:
  port: ${PORT:8080}

logging:
  level:
    root: ERROR

JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m -XX:MaxMetaspaceSize=64m -XX:+UseSerialGC -Djava.awt.headless=true"